### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by sys1yagi** [sys1yagi/mastodon-android#4]
# todo

- [x] impelement mostdon4j-rx
- [x] get public timeline and show list
- [x] add VIPER architecture and templates
- [ ] add auth sequence
  - implement login api 
  - walk-throgh
